---
title: "How fast is aorsf?"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How fast is aorsf?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(aorsf)
```



```{r}

time_obliqueRSF <- system.time(
 obliqueRSF::ORSF(data = pbc_orsf, 
                  ntree = 250, 
                  verbose = FALSE)
)

time_aorsf <- system.time(
 orsf(Surv(time, status) ~ ., 
      data = pbc_orsf, 
      n_tree = 250, 
      oobag_pred = FALSE)
)

time_obliqueRSF['elapsed'] / time_aorsf['elapsed']

```



This technique scales well - it is as fast as the routines in `randomForestSRC`

```{r}

time_rfsrc <- system.time(
 randomForestSRC::rfsrc(Surv(time, status) ~ ., 
                        data = pbc_orsf, 
                        ntree = 500, 
                        nodesize = 15,
                        importance = TRUE)
)

time_aorsf <- system.time(
 orsf(Surv(time, status) ~ ., 
      data = pbc_orsf, 
      n_tree = 500, 
      importance = TRUE)
)

time_rfsrc['elapsed'] / time_aorsf['elapsed']

```
