# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_node_name <- function(part) {
    .Call(`_orsf2_make_node_name`, part)
}

leaf_surv_small <- function() {
    .Call(`_orsf2_leaf_surv_small`)
}

cholesky <- function() {
    invisible(.Call(`_orsf2_cholesky`))
}

cholesky_solve <- function() {
    invisible(.Call(`_orsf2_cholesky_solve`))
}

cholesky_invert <- function() {
    invisible(.Call(`_orsf2_cholesky_invert`))
}

newtraph_cph_iter <- function(beta) {
    .Call(`_orsf2_newtraph_cph_iter`, beta)
}

newtraph_cph_init <- function() {
    .Call(`_orsf2_newtraph_cph_init`)
}

newtraph_cph <- function() {
    .Call(`_orsf2_newtraph_cph`)
}

lrt_multi <- function() {
    .Call(`_orsf2_lrt_multi`)
}

ostree_fit <- function() {
    .Call(`_orsf2_ostree_fit`)
}

orsf_fit <- function(x, y, n_split_ = 5L, mtry_ = 4L, leaf_min_events_ = 5, leaf_min_obs_ = 10, cph_method_ = 1L, cph_eps_ = 1e-8, cph_iter_max_ = 7L, cph_pval_max_ = 0.95) {
    .Call(`_orsf2_orsf_fit`, x, y, n_split_, mtry_, leaf_min_events_, leaf_min_obs_, cph_method_, cph_eps_, cph_iter_max_, cph_pval_max_)
}

